"""Shared Core enums. Python types are not language-neutral architectural contracts."""

from enum import Enum, IntEnum


class ActorType(Enum):
    HUMAN_OPERATOR = "HUMAN_OPERATOR"
    CONTROL_PLANE = "CONTROL_PLANE"
    WORKER = "WORKER"
    INTEGRATION = "INTEGRATION"


class AuthorizationSourceState(Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class ScopeDecision(Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_HUMAN_REVIEW = "REQUIRE_HUMAN_REVIEW"


class ScopeClassification(Enum):
    IN_SCOPE = "IN_SCOPE"
    UNKNOWN = "UNKNOWN"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class ScopeRuleEffect(Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    UNKNOWN = "UNKNOWN"


class SideEffectLevel(IntEnum):
    LEVEL_0 = 0
    LEVEL_1 = 1
    LEVEL_2 = 2
    LEVEL_3 = 3


class ApprovalDecision(Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class ExecutionDecisionKind(Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_HUMAN_REVIEW = "REQUIRE_HUMAN_REVIEW"


class ReasonCode(Enum):
    ALLOWED = "ALLOWED"
    AUTHORIZATION_MISSING = "AUTHORIZATION_MISSING"
    AUTHORIZATION_INACTIVE = "AUTHORIZATION_INACTIVE"
    SCOPE_DENIED = "SCOPE_DENIED"
    SCOPE_NOT_EXPLICITLY_ALLOWED = "SCOPE_NOT_EXPLICITLY_ALLOWED"
    SCOPE_AMBIGUOUS = "SCOPE_AMBIGUOUS"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    BUDGET_MISMATCH = "BUDGET_MISMATCH"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_INVALID_ACTOR = "APPROVAL_INVALID_ACTOR"
    APPROVAL_SUBJECT_MISMATCH = "APPROVAL_SUBJECT_MISMATCH"
    APPROVAL_NOT_RECORDED = "APPROVAL_NOT_RECORDED"
    SIDE_EFFECT_LEVEL_DENIED = "SIDE_EFFECT_LEVEL_DENIED"
    CAPABILITY_AUTHORIZATION_MISSING = "CAPABILITY_AUTHORIZATION_MISSING"
    UNKNOWN_CAPABILITY = "UNKNOWN_CAPABILITY"
    UNKNOWN_ACTION = "UNKNOWN_ACTION"
    UNSUPPORTED_CAPABILITY_VERSION = "UNSUPPORTED_CAPABILITY_VERSION"
    DEFINITION_FINGERPRINT_MISMATCH = "DEFINITION_FINGERPRINT_MISMATCH"
    RISK_UNDERSTATEMENT = "RISK_UNDERSTATEMENT"
    RISK_EXCEEDS_CAPABILITY = "RISK_EXCEEDS_CAPABILITY"
    SIDE_EFFECT_BINDING_MISMATCH = "SIDE_EFFECT_BINDING_MISMATCH"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    SCOPE_PATH_AMBIGUOUS = "SCOPE_PATH_AMBIGUOUS"
    SCOPE_NORMALIZATION_INVALID = "SCOPE_NORMALIZATION_INVALID"
    SCOPE_USERINFO_DENIED = "SCOPE_USERINFO_DENIED"
    SCOPE_WILDCARD_REJECTED = "SCOPE_WILDCARD_REJECTED"
    SCOPE_UNKNOWN_CLASSIFICATION = "SCOPE_UNKNOWN_CLASSIFICATION"
    SCOPE_EXPIRED = "SCOPE_EXPIRED"
    PROGRAM_POLICY_DENIED = "PROGRAM_POLICY_DENIED"
    RATE_LIMIT_DENIED = "RATE_LIMIT_DENIED"
    SENSOR_TIMEOUT = "SENSOR_TIMEOUT"
    SENSOR_FAILED = "SENSOR_FAILED"
    CENSUS_ALLOWED = "CENSUS_ALLOWED"
    CENSUS_DENIED = "CENSUS_DENIED"
    IMPACT_CHAIN_MISSING = "IMPACT_CHAIN_MISSING"
    IMPACT_CHAIN_CROSS_RUN = "IMPACT_CHAIN_CROSS_RUN"
    CROSS_RUN_PROOF = "CROSS_RUN_PROOF"
