"""Phase 7 failure/recovery census. Not a second scheduler and not auto-retry."""

from __future__ import annotations

FAILURE_CENSUS_COMPLETE = True

FAILURE_CENSUS = (
    {
        "name": "LocalRunSupervisorRegistry",
        "module": "zest.application.local_run_supervisor",
        "owner": "zestd / research_run_control",
        "durable_state": "orchestration lease + research_orchestrations",
        "process_local": "in-memory supervisor map",
        "idempotency_key": "research_run_id lease epoch",
        "recovery": "ClassifyRuntimeRecovery then lease attach; never auto-retry DISPATCHING/UNKNOWN",
        "ambiguity": "expired lease is not operational failure",
        "gap": "none for attach; UNKNOWN remains human/recon",
    },
    {
        "name": "ARC step/recovery",
        "module": "zest.application.autonomous_research_controller",
        "owner": "ARC",
        "durable_state": "research_orchestrations phase/checkpoint ids",
        "process_local": "none; tick reloads from SoR",
        "idempotency_key": "last_experiment_id / last_hypothesis_id / request_id",
        "recovery": "resume from phase; UNKNOWN_OUTCOME_REQUIRES_REVIEW fail-closed",
        "ambiguity": "DISPATCHING crash is unknown external result",
        "gap": "none; unknown_outcome_open now wired into next_cycle_action",
    },
    {
        "name": "ReconcileResearchRun",
        "module": "zest.application.reconcile_research_run",
        "owner": "control plane",
        "durable_state": "execution_attempts + orchestration",
        "process_local": "none",
        "idempotency_key": "attempt_id",
        "recovery": "classify AUTHORIZED vs DISPATCHING vs UNKNOWN; no side-effect guess",
        "ambiguity": "AUTHORIZED SE>0 requires human",
        "gap": "none",
    },
    {
        "name": "ClassifyRuntimeRecovery",
        "module": "zest.application.classify_runtime_recovery",
        "owner": "zestd attach",
        "durable_state": "attempts + orchestration state",
        "process_local": "none",
        "idempotency_key": "research_run_id",
        "recovery": "SAFE_RESUME / HUMAN_REQUIRED / RECONCILIATION_REQUIRED / DO_NOT_RESUME",
        "ambiguity": "SE0 UNKNOWN is still not proof of no contact",
        "gap": "none",
    },
    {
        "name": "retry_policy",
        "module": "zest.application.retry_policy",
        "owner": "control plane",
        "durable_state": "attempt state + target_contact_status",
        "process_local": "none",
        "idempotency_key": "attempt_id",
        "recovery": "automatic_retry_allowed always False; classify only",
        "ambiguity": "none",
        "gap": "none",
    },
    {
        "name": "ExecutePlannedExperiment",
        "module": "zest.application.execute_planned_experiment",
        "owner": "ARC dispatch",
        "durable_state": "execution_attempts request_id unique, WorkerResult request_id unique",
        "process_local": "in-flight worker handle",
        "idempotency_key": "request_id",
        "recovery": "crash after dispatch → UNKNOWN_OUTCOME; no Observation from unknown",
        "ambiguity": "external side effect may have occurred",
        "gap": "none",
    },
    {
        "name": "ProposeResearchHypothesis UoW",
        "module": "zest.application.propose_research_hypothesis",
        "owner": "Research",
        "durable_state": "research_reasoning + research_admissions + hypotheses",
        "process_local": "model call",
        "idempotency_key": "context_fingerprint + correlation_id",
        "recovery": "replay admitted cycle; exploratory persist after outer UoW closes",
        "ambiguity": "rejected admissions persist without hypothesis",
        "gap": "nested return-inside-open fixed in 6.9/7",
    },
    {
        "name": "OAST arm/callback/timeout",
        "module": "zest.application.admit_oast_callback / oast_timeout",
        "owner": "OAST application",
        "durable_state": "oast_correlations, deliveries, admissions",
        "process_local": "listener",
        "idempotency_key": "provider_event + correlation digest",
        "recovery": "unknown token audited; expired delivery retained; timeout audit",
        "ambiguity": "late callback after timeout is not evidence",
        "gap": "binding rejects now persist OAST_CALLBACK_REJECTED",
    },
    {
        "name": "Evidence/Candidate/Verification/Proposal",
        "module": "promotion_pipeline / propose_candidate / start_candidate_verification / submit_finding_proposal",
        "owner": "Research promotion",
        "durable_state": "UQ per evidence, candidate evidence, verification candidate, proposal candidate",
        "process_local": "none",
        "idempotency_key": "constraint names in zest.data.uniqueness",
        "recovery": "conflict returns existing; OPEN cannot propose finding",
        "ambiguity": "VALIDATED is not Finding",
        "gap": "none",
    },
    {
        "name": "Completion guard",
        "module": "zest.application.global_research_work_audit",
        "owner": "ARC empty tick",
        "durable_state": "inventory ints + completion_block_reasons",
        "process_local": "none",
        "idempotency_key": "research_run_id",
        "recovery": "completion_allowed false until blockers terminal",
        "ambiguity": "protocol Core deny is blocked work not coverage",
        "gap": "Phase 7 exposes dispatching/in_flight/orphan kinds",
    },
    {
        "name": "Orchestration obligations",
        "module": "zest.application.orchestration_obligations",
        "owner": "ARC natural completion",
        "durable_state": "attempts + experiments + worker_results",
        "process_local": "none",
        "idempotency_key": "attempt_id / experiment_id",
        "recovery": "UNKNOWN_OUTCOME and open experiments block complete",
        "ambiguity": "none",
        "gap": "none",
    },
    {
        "name": "PostgreSQL uniqueness",
        "module": "zest.data.uniqueness / postgres tables",
        "owner": "SoR",
        "durable_state": "named unique constraints",
        "process_local": "none",
        "idempotency_key": "constraint_name on PersistenceConflictError",
        "recovery": "callers catch only named conflicts",
        "ambiguity": "none",
        "gap": "none",
    },
)

FAILURE_CENSUS_GAPS_OPEN = 0
