"""Phase 7 lifecycle state classification. Terminal success is never UNKNOWN."""

from __future__ import annotations

STATE_MACHINE_MATRIX_COMPLETE = True

# terminal_* flags are exclusive of non_terminal. retriable means automatic retry
# is allowed by retry_policy — almost always False for side-effecting work.

STATE_MACHINE_MATRIX = (
    {
        "record": "ResearchWork/Opportunity",
        "non_terminal": ("PENDING", "SELECTED"),
        "terminal_success": ("ADMITTED",),
        "terminal_negative": ("NOT_ADMITTED",),
        "terminal_blocked": ("BLOCKED_POLICY",),
        "terminal_unknown": (),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "Selection",
        "non_terminal": (),
        "terminal_success": ("SELECT",),
        "terminal_negative": ("SKIP_DUPLICATE", "SKIP_LOW_INFORMATION"),
        "terminal_blocked": ("BLOCKED_BUDGET", "BLOCKED_POLICY"),
        "terminal_unknown": ("NEEDS_MORE_CONTEXT",),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "ExperimentPlan",
        "non_terminal": ("planned",),
        "terminal_success": (),
        "terminal_negative": (),
        "terminal_blocked": (),
        "terminal_unknown": (),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "CoreDecision",
        "non_terminal": (),
        "terminal_success": ("ALLOW",),
        "terminal_negative": ("DENY",),
        "terminal_blocked": ("DENY",),
        "terminal_unknown": (),
        "terminal_human_wait": ("REQUIRE_HUMAN_REVIEW",),
        "terminal_authority_blocked": ("DENY",),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "WorkerAttempt",
        "non_terminal": ("AUTHORIZED", "DISPATCHING"),
        "terminal_success": ("COMPLETED",),
        "terminal_negative": ("FAILED", "TIMED_OUT", "CANCELLED"),
        "terminal_blocked": (),
        "terminal_unknown": ("UNKNOWN_OUTCOME", "DISPATCHING-after-crash"),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "WorkerResult",
        "non_terminal": (),
        "terminal_success": ("SUCCEEDED",),
        "terminal_negative": ("FAILED", "TIMED_OUT"),
        "terminal_blocked": ("REAUTHORIZATION_REQUIRED",),
        "terminal_unknown": (),
        "terminal_human_wait": ("REAUTHORIZATION_REQUIRED",),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "Observation",
        "non_terminal": (),
        "terminal_success": ("persisted",),
        "terminal_negative": (),
        "terminal_blocked": (),
        "terminal_unknown": (),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "Assessment",
        "non_terminal": (),
        "terminal_success": ("CONSISTENT_WITH_PREDICTION", "INCONSISTENT_WITH_PREDICTION"),
        "terminal_negative": ("INVOCATION_FAILED",),
        "terminal_blocked": (),
        "terminal_unknown": ("UNKNOWN_OUTCOME",),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "Evidence",
        "non_terminal": (),
        "terminal_success": ("admitted",),
        "terminal_negative": ("rejected",),
        "terminal_blocked": (),
        "terminal_unknown": (),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "Candidate",
        "non_terminal": ("OPEN", "VERIFYING"),
        "terminal_success": ("VALIDATED",),
        "terminal_negative": ("REJECTED", "DUPLICATE", "OUT_OF_SCOPE"),
        "terminal_blocked": (),
        "terminal_unknown": ("INCONCLUSIVE",),
        "terminal_human_wait": (),
        "terminal_authority_blocked": ("OUT_OF_SCOPE",),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "Verification",
        "non_terminal": ("planned",),
        "terminal_success": ("VERIFIED/VALIDATED",),
        "terminal_negative": ("DISPROVEN/REJECTED",),
        "terminal_blocked": ("BLOCKED_BY_AUTHORITY",),
        "terminal_unknown": ("INCONCLUSIVE", "UNKNOWN_OUTCOME"),
        "terminal_human_wait": ("NEEDS_HUMAN_REVIEW",),
        "terminal_authority_blocked": ("BLOCKED_BY_AUTHORITY",),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "FindingProposal",
        "non_terminal": ("PROPOSED", "HUMAN_REVIEW"),
        "terminal_success": ("APPROVED",),
        "terminal_negative": ("REJECTED",),
        "terminal_blocked": (),
        "terminal_unknown": (),
        "terminal_human_wait": ("HUMAN_REVIEW",),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "HumanReview",
        "non_terminal": ("open",),
        "terminal_success": ("approved",),
        "terminal_negative": ("denied",),
        "terminal_blocked": (),
        "terminal_unknown": (),
        "terminal_human_wait": ("open",),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "OastArm",
        "non_terminal": ("armed waiting callback",),
        "terminal_success": ("correlated admission",),
        "terminal_negative": ("no-callback timeout",),
        "terminal_blocked": (),
        "terminal_unknown": ("unknown token",),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": True,
        "requires_correlation": True,
    },
    {
        "record": "OastCallback",
        "non_terminal": (),
        "terminal_success": ("admitted",),
        "terminal_negative": ("rejected expired/unknown/wrong-run",),
        "terminal_blocked": (),
        "terminal_unknown": ("unknown token",),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": True,
    },
    {
        "record": "ModelReasoning",
        "non_terminal": (),
        "terminal_success": ("ADMITTED",),
        "terminal_negative": ("REJECTED_*", "NEEDS_MORE_CONTEXT", "MODEL_INVOCATION_FAILED"),
        "terminal_blocked": ("CONTENT_POLICY_BLOCKED",),
        "terminal_unknown": (),
        "terminal_human_wait": (),
        "terminal_authority_blocked": (),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
    {
        "record": "CompletionGuard",
        "non_terminal": ("completion_allowed=false",),
        "terminal_success": ("COMPLETED_NO_MORE_OPPORTUNITIES",),
        "terminal_negative": (),
        "terminal_blocked": ("COMPLETED_UNDER_CURRENT_AUTHORITY_WITH_BLOCKED_WORK",),
        "terminal_unknown": ("UNKNOWN_OUTCOME_REQUIRES_REVIEW",),
        "terminal_human_wait": ("REQUIRE_HUMAN_REVIEW",),
        "terminal_authority_blocked": ("CORE_BLOCKED",),
        "retriable": False,
        "requires_timeout": False,
        "requires_correlation": False,
    },
)
