"""Explicit sensor/input ownership. No ambiguous ingestion."""

from __future__ import annotations

SENSOR_OWNERSHIP_MATRIX = (
    {
        "sensor": "Browser network events",
        "ingestion": "browser worker / sensor observation repo",
        "normalize": "discovery/HTTP observation adapters",
        "correlate": "research run + target_reference",
        "observation": "Admit path after WorkerResult",
        "evidence": "never directly",
        "coverage": "hunter/coverage feedback after assessment",
        "dedupe": "payload_digest + observation_id uniqueness",
        "recovery": "sensor_observations list_for_research_run",
        "redaction": "safe_data redact on model context; SoR rejects secret keys on ObservationRecord",
    },
    {
        "sensor": "OAST callbacks",
        "ingestion": "AdmitOastCallback / callback delivery repo",
        "normalize": "bounded normalized_payload",
        "correlate": "OastCorrelationRecord + token_id",
        "observation": "only after known-token admission",
        "evidence": "EVIDENCE_PIPELINE_PENDING",
        "coverage": "apply_oast_coverage_feedback",
        "dedupe": "provider_event uniqueness",
        "recovery": "deliveries + admissions append-only",
        "redaction": "no raw OAST secrets in model context",
    },
    {
        "sensor": "protocol raw results",
        "ingestion": "Protocol Worker when Core allows",
        "normalize": "protocol.parser.step evaluator",
        "correlate": "experiment_id",
        "observation": "WorkerResult → Observation",
        "evidence": "NOT_EVIDENCE; SE3 Core deny is not coverage",
        "coverage": "mutation_protocol_feedback",
        "dedupe": "experiment uniqueness",
        "recovery": "attempts + worker_results",
        "redaction": "no secrets in envelopes",
    },
    {
        "sensor": "external adapters / interactsh",
        "ingestion": "OAST provider adapter → callback delivery",
        "normalize": "AdmitOastCallback",
        "correlate": "correlation digest",
        "observation": "after admission",
        "evidence": "EVIDENCE_PIPELINE_PENDING",
        "coverage": "OAST coverage audit",
        "dedupe": "provider_event_id",
        "recovery": "oast_callback_deliveries",
        "redaction": "secret keys rejected on payload",
    },
    {
        "sensor": "session material",
        "ingestion": "session_contexts",
        "normalize": "identity catalog references",
        "correlate": "identity_id",
        "observation": "never stores cookies/tokens",
        "evidence": "NOT_EVIDENCE",
        "coverage": "auth missing-precondition audits",
        "dedupe": "session_context_id",
        "recovery": "session_contexts list_for_research_run",
        "redaction": "secret_scheme/name references only",
    },
    {
        "sensor": "worker observations",
        "ingestion": "ExecutePlannedExperiment",
        "normalize": "capability-specific observer",
        "correlate": "worker_result_id",
        "observation": "ObservationRecord insert",
        "evidence": "via PromotionPipeline if strategy supported",
        "coverage": "engine-specific feedback",
        "dedupe": "UQ on experiment/observation",
        "recovery": "worker_results + observations",
        "redaction": "ObservationRecord rejects secret keys",
    },
    {
        "sensor": "admission hooks",
        "ingestion": "admit_hypothesis / admit_evidence / admit_candidate",
        "normalize": "Research domain",
        "correlate": "research_run_id",
        "observation": "never from model claim alone",
        "evidence": "admit_evidence only",
        "coverage": "promotion run stages",
        "dedupe": "UQ_EVIDENCE_EXPERIMENT_SUPPORTING",
        "recovery": "admission records append-only",
        "redaction": "forbidden evidence keys",
    },
    {
        "sensor": "model outputs",
        "ingestion": "ProposeResearchHypothesis",
        "normalize": "structured contracts",
        "correlate": "context_fingerprint",
        "observation": "never",
        "evidence": "never from model-only claim",
        "coverage": "HYPOTHESIS_FOLLOWUP via global scheduler",
        "dedupe": "replay by context fingerprint",
        "recovery": "research_reasoning + research_admissions",
        "redaction": "RUNTIME_SECRET_KEYS / TARGET_MODEL_SECRET_KEYS",
    },
    {
        "sensor": "diagnostic signals",
        "ingestion": "diagnostic.echo Worker",
        "normalize": "DiagnosticEchoEvaluator",
        "correlate": "experiment_id",
        "observation": "echo observation",
        "evidence": "SUPPORTED_NOW plumbing evidence",
        "coverage": "not vulnerability coverage",
        "dedupe": "assessment uniqueness",
        "recovery": "promotion pipeline stages",
        "redaction": "no secrets in echo payload",
    },
)
